### ISSUE TITLE
Support `additionalProperties: true`

### ISSUE THREAD

**Issue by ajenkins-cargometrics** [ferdikoomen/openapi-typescript-codegen#1154]
In OpenAPI 3, a schema like:

```yaml
    AnyValues:
      description: An object whose property values can be of any type
      type: object
      additionalProperties: true
```

Should be equivalent to a typescript type like:

```typescript
type AnyValues = {
    [key: string]: any
};
```

However what openapi-typescript-codegen actually generates is a type like this:

```typescript
type AnyValues = {
};
```

That is, an object with no properties.

Additionally, OpenAPI allows combining `additionalProperties: true` with explicit property definitions.  So an OpenAPI schema like this:

```yaml
SomeType:
    type: object
    required: [name]
    properties:
        name:
            type: string
    additionalProperties: true
```

Should result in a typescript type like:

```typescript
type SomeType = {
    name: string,
    [key: string]: any
};
```

but in fact it results in:

```typescript
type SomeType = {
    name: string
};
```

Desired result: `additionalProperties: true` in an object schema should result in a `[key: string]: any` property in the corresponding typescript type.

**Comment by garcipat** [comment]
This is seems to be related to this one: #1066

**Comment by ajenkinski** [comment]
> This is seems to be related to this one: #1066

That issue is different.  In that case, the problem is that the spec doesn't specify a type for the schemas.  That is, it has types defined like

```yaml
  schemas:
    Account:
      properties:
        balance:
          type: string
          description: balance in unit WEI, presented with hex string
          example: '0x47ff1f90327aa0f8e'
        energy:
          type: string
          description: energy in uint WEI, presented with hex string
          example: '0xcf624158d591398'
        hasCode:
          type: boolean
          description: whether the account has code
          example: false
```
Simply adding `type: object` to the type fixes the problem.  I'm not sure if the `type` field is supposed to be optional, but in any case it's a different problem.
