### ISSUE TITLE
Exclude endpoints from Client

### ISSUE THREAD

**Issue by tsoffereins** [ferdikoomen/openapi-typescript-codegen#1272]
The Serverless Application Model from AWS offers me the possibility to define the endpoints on an HTTP Gateway by using an `openapi.yaml` file.

I love that I can use the same file to generate a Typescript Client, but not all endpoints (operations) are meant for the consumer of this Client (e.g. a swagger docs or a private endpoint).

For example (tags indicate issue):
```yaml
paths:
  /:
    get:
      tags:
        - "exclude-from-client"
      description: "Serves swagger documentation"
  /articles:
    get:
      tags:
        - "articles"
      description: "Returns a list of all items"
  /articles:
    post:
      tags:
        - "articles"
        - "exclude-from-client"
      description: "Creates a new article"
```

I browsed the source code, but could not find any option that allows me to achieve this. I would like to have an option to exclude them by either tag (excludes a service, `--excludeServices`) or operation id (excludes an endpoint, `--excludeOperations`).

Has this feature yet been considered?
