### ISSUE TITLE
Apparently there is no option to generate non nullable model properties

### ISSUE THREAD

**Issue by gyozob** [ferdikoomen/openapi-typescript-codegen#1365]
Hello, is there a way to generate non nullable model properties? Whatever I do it always generates as nullable.
```
// Current
export type SampleModel= {
    title?: string;
    url?: string;
};

// Expected
export type SampleModel= {
    title: string;
    url: string;
};
```
In my swagger json I also added these properties as required but I got the same result.
I'm using this command 
```npx openapi-typescript-codegen --input $swaggerUrl --output ./src/interfaces/--exportCore=false --exportServices=false```

**Comment by predrag-codetribe** [comment]
Yes, instead of:

```yaml
SampleModel:
    type: object
    properties:
      title:
        type: string
      url:
        type: string

```
Use:
```yaml
SampleModel:
    required:
      - title
      - url
    type: object
    properties:
      title:
        type: string
      url:
        type: string

```
See the [spec](https://swagger.io/docs/specification/data-models/data-types/#required) for more info.
