### ISSUE TITLE
Compile error with default value for string enum

### ISSUE THREAD

**Issue by dieseldjango** [ferdikoomen/openapi-typescript-codegen#1444]
**Describe the bug**
I have the following string enum schema for a query parameter with a default value:
```
   OrderByDirection:
      description: The sort order for query results.
      type: string
      enum: [asc, desc]
      default: desc
```
The generated client doesn't compile because you can't assign a string literal to an enum:
```
TSError: ⨯ Unable to compile TypeScript:
../shared/src/ApiClient/services/V1Service.ts:24:9 - error TS2322: Type '"desc"' is not assignable to type 'OrderByDirection'.

24         orderByDirection: OrderByDirection = 'desc',
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
