### ISSUE TITLE
Default values of 0 do not get generated

### ISSUE THREAD

**Issue by seriouslag** [ferdikoomen/openapi-typescript-codegen#1558]
If a default value of 0 is specified then it is not generated. I traced it to this line but I do not yet know .hbs if someone wants to take a stab at correcting this.

A workaround is to set a default value as "0" and set the type to a number or integer and then it will be populated.

https://github.com/ferdikoomen/openapi-typescript-codegen/blob/a0807fa78d7c19ae90985e63c32caaf1e04f2581/src/templates/partials/parameters.hbs#L5

example:

```yaml
limit:
  name: limit
  in: query
  required: false
  schema:
    type: integer
    format: int32
    default: 25
page:
  name: page
  in: query
  required: false
  schema:
    type: integer
    format: int32
    default: 0
```

*Generated*
```typescript
    public getMyStuff({
        page,
        limit = 25,
    }: {
    ...
    }
```

'limit' would be generated with a default value of 25 but 'page' would not have a default value.

the workaround would look like this

```yaml
limit:
  name: limit
  in: query
  required: false
  schema:
    type: integer
    format: int32
    default: '25'
page:
  name: page
  in: query
  required: false
  schema:
    type: integer
    format: int32
    default: '0'
```

*Generated*
```typescript
    public getMyStuff({
        page = 0,
        limit = 25,
    }: {
    ...
    }
```
