### ISSUE TITLE
Duplicate parameter name (query/header)

### ISSUE THREAD

**Issue by eLvErDe** [ferdikoomen/openapi-typescript-codegen#1617]
Hello,

Here is the generated code (cannot compile):

```typescript
    /**
     * Listen for reconfiguration messages for the given app_id/client_id (WebSocket)
     * @param appId Client application identifier
     * @param clientId Client ws consumer identifier
     * @param bearer Valid JWT access token (Websocket cannot use HTTP headers, use either cookie or query param)
     * @param bearer Valid JWT access token (Websocket cannot use HTTP headers, use either cookie or query param)
     * @returns void
     * @throws ApiError
     */
    public getCameraApiV2LayoutWsClient(
        appId: string,
        clientId: string,
        bearer?: string,
        bearer?: string,
       ...
```

Original OpenAPI spec has the following snippet leading to this:

```yaml
        parameters:
        - name: app_id
          in: path
          description: Client application identifier
          required: true
          schema:
            type: string
        - name: client_id
          in: path
          description: Client ws consumer identifier
          required: true
          schema:
            type: string
        - name: Bearer
          in: cookie
          description: Valid JWT access token (Websocket cannot use HTTP headers, use either cookie or query param)
          required: false
          schema:
            type: string
        - name: Bearer
          in: query
          description: Valid JWT access token (Websocket cannot use HTTP headers, use either cookie or query param)
          required: false
          schema:
            type: string
```

Thanks !
