### ISSUE TITLE
handle blank enum

### ISSUE THREAD

**Issue by stefanprobst** [ferdikoomen/openapi-typescript-codegen#1636]
i am getting the following from a django restframework generated openapi doc:

```yaml
components:
  schemas:
    BlankEnum:
      enum:
        - ''
    NullEnum:
      enum:
        - null
```

which this generator transforms into:

```ts
// src/api/models/BlankEnum.ts
export enum BlankEnum {
    = '',
}
```

and

```ts
// src/api/models/NullEnum.ts
export type NullEnum = {
};
```

note how `src/api/models/BlankEnum.ts` is invalid syntax and causes a compile error
