### ISSUE TITLE
Use union types instead of enums

### ISSUE THREAD

**Issue by KevinHerklotz** [ferdikoomen/openapi-typescript-codegen#366]
# Description

Instead of generating [enum types](https://www.typescriptlang.org/docs/handbook/enums.html) I would like to have an option to generate [union types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#union-types) instead.
If you like the idea **I am very happy to implement this** and create a PR.

# Example 
YAML model:
``` yaml
    [...]
    schemas:
        Rating:
            type: object
            properties:
                id:
                    type: string
                value:
                    type: string
                    enum:
                        - negative
                        - neutral
                        - positive
```

### Generated model
``` ts
export interface Rating {
    id?: string;
    value?: Rating.value;
}

export namespace Rating {
    export enum value {
        NEGATIVE = 'negative',
        NEUTRAL = 'neutral',
        POSITIVE = 'positive',
    }
}
```

### Usage
If I want to use this in my code I have to do this:
``` ts
const exampleRating: Rating = {
  id: '364363313',
  value: Rating.value.NEUTRAL,
}
```

### Generated model
``` ts
export interface Rating {
    id?: string;
    value?: 'positive' | 'neutral'  | 'negative'; // no enum anymore, instead we use union types
}
```

### Usage
If I want to use this in my code I can do it much simpler now:
``` ts
const exampleRating: Rating = {
  id: '364363313',
  value: 'neutral', // much simpler in my opinion, TS would still complain if I would use something that is not allowed
}
```

# Explanation
Of course this would be behind a feature flag. At the beginning I thought `useUnionTypes` is doing that, but it is not, so I have to find another name for my feature. I thought about `useUnionTypesForEnums`, but I'm open for better suggestions.
