### ISSUE TITLE
big with required type

### ISSUE THREAD

**Issue by euhoo** [ferdikoomen/openapi-typescript-codegen#505]
I'm using yaml to generate interface.
This code from yaml
```
User:
      required:
        boss_id
        cust_boss
      type: object
      properties:
        boss:
          type: User
        boss_id:
          type: number
        cust_boss:
          type: User
```
transforms to typescript

```
export type User = {
    boss: User;
    boss_id: number;
    cust_boss: User;
}
```
As you can see boss became required in ts type.
The same thing if only boss_id required in yaml
The same thing if only cust_boss required in yaml
