### ISSUE TITLE
boolean property with default: false became required

### ISSUE THREAD

**Issue by Ti-webdev** [ferdikoomen/openapi-typescript-codegen#636]
My schema is:
```yaml
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: byte
          description: base64-encoded password
        remember:
          type: boolean
          default: false
      required:
        - email
        - password
```

it's generated to:
```typescript
$AuthRequest = {
    properties: {
        email: {
            type: 'string',
            isRequired: true,
            format: 'email',
        },
        password: {
            type: 'string',
            isRequired: true,
            format: 'byte',
        },
        remember: {
            type: 'boolean',
            isRequired: true,
        },
    },
};
```

`remember` is marked as `isRequired: true` but it isn't required.
