### ISSUE TITLE
Add support for the `explode` query parameters

### ISSUE THREAD

**Issue by sjoerdmulder** [ferdikoomen/openapi-typescript-codegen#654]
I don't see that the `explode` definitions don't have any connection in the code currently.

Is it possible to add this support specified here: https://swagger.io/docs/specification/serialization/#query 

What would be nice that the service API would expose `explode` as `Array<number>` instead of the `number` it is currently generated, so that you can easily pass multiple values.

**Comment by ferdikoomen** [comment]
@sjoerdmulder Yes, great idea, we have a similar problem with the FormData. See the ticket here: https://github.com/ferdikoomen/openapi-typescript-codegen/issues/658
I haven't prioritised this, since most projects I'm working on use JSON bodies for FormData and 'default' encoding for query params.

**Comment by sjoerdmulder** [comment]
Great I already have some POC code ready, will prepare a PR later this week

Op di 27 apr. 2021 13:41 schreef Ferdi Koomen ***@***.***>:

**Comment by microHoffman** [comment]
Hey @ferdikoomen @sjoerdmulder , I have problem that is most likely related to this. Codegen incorrectly transforms the following:
```yaml
        - in: query
          name: status__in
          schema:
            type: array
            items:
              type: number
          description: Multiple values may be separated by commas.
          explode: false
          style: form
```
into e.g.: `...?status__in=2&status__in=3`... While the correct one should be `status__in=2,3`.

The problem is described here as well (https://github.com/tfranzel/drf-spectacular/issues/599) with the explanation. Right now I need to hardcode the `status__in` parameter as comma-separated stringified values to have the query params value in correct format. Do you plan to implement this feature please? Thank you for any info, appreciate your work.
