### ISSUE TITLE
Support for API_KEY, different base paths and custom fetch ? 

### ISSUE THREAD

**Issue by christopheblin** [ferdikoomen/openapi-typescript-codegen#904]
With the openapi-generator from openapitools with typescript-fetch, I can do this : 

```
this._myApi = new MyApi(
      new Configuration({
        apiKey: _config.env.MY_API_KEY,
        basePath: _config.env.MY_API_ENDPOINT,
        fetchApi: (url: string, init?: RequestInit | undefined) =>
          this._fetch(url, init),
      }),
    );
```

First, because the v3 spec contains a definition for api_key, it automatically adds this in each operation
```
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: Mandatory Application token
      in: query
      name: api_key
```

I do not see any support for this currently : is this correct ?

Second, I can override the basePath of the API (so if it is deployed in staging and prod with 2 different URLs, I can just swap at runtime without regenerating the sources)

I see that currently the generated source contains BASE: 'xxx' with xxx coing from servers[0].url of the spec, I can override this at runtime with `OpenAPI.BASE = _config.env.MY_API_ENDPOINT;` : is this correct to do it like this ?

Third, I can provide my own "fetch" (which I use especially to mock the fetch during tests).

I do not see any support for this currently : is this correct ?
