### ISSUE TITLE
Generate valid TS type definitions for empty model properties

### ISSUE THREAD

**Issue by vyobukhov** [ferdikoomen/openapi-typescript-codegen#963]
We have a pretty weird yet totally valid OpenAPI model that we have no control at. This is just an example of this model:
```yaml
FooBarModel:
  type: object
  required:
  - all
  properties:
    all: !ref self.AnotherModel
    foo: !ref self.AnotherModel
    bar: !ref self.AnotherModel
    '': !ref self.AnotherModel
```

It's not done by mistake, it's an actual data format that we receive from a large enterprise API. 

Right now TS definitions generated from this model are invalid because empty string is not escaped:
```typescript
export type FooBarModel = {
  all: AnotherModel;
  foo: AnotherModel;
  bar: AnotherModel;
  ?: AnotherModel;
};
```

instead definition should look like this:
```typescript
export type FooBarModel = {
  all: AnotherModel;
  foo: AnotherModel;
  bar: AnotherModel;
  ''?: AnotherModel;
};
```

Yes, it's a weird model and weird TS definition, but it's completely valid both in OpenAPI and TS/JS world.
I've created PR #962 for this, hope it will be merged and we can fix this issue in our code. Thank you.
