### ISSUE TITLE
Using complex dictionaries within compositions (oneOf, anyOf, allOf) generates wrong code

### ISSUE THREAD

**Issue by nikopavlica** [ferdikoomen/openapi-typescript-codegen#964]
There is an issue generating code that contains complex [dictionaries](https://swagger.io/docs/specification/data-models/dictionaries/) (dictionaries that themselves contain `oneOf`, `anyOf` or `allOf`) within compositions (`oneOf`, `anyOf` or `allOf`).

This spec:
```yaml
CompositionWithOneOfAndDictionary:
  description: This is a model that contains a dictionary within composition
  type: object
  properties:
    propA:
      oneOf:
      - type: boolean
      - type: object
        additionalProperties:
          type: array
          items:
            oneOf:
            - type: boolean
            - type: string
```
should generate :
```typescript
export type CompositionWithOneOfAndDictionary = {
    propA?: (boolean | Record<string, Array<(boolean | string)>>);
};
```
but instead generates:
```typescript
export type CompositionWithOneOfAndDictionary = {
    propA?: boolean;
};
```

If i replace nested array of `boolean` or `string` into a simple array (eg. of `string`), it works as expected.

Proposed fix: #965
