### ISSUE TITLE
Discriminators not working for oneOf when the members are allOf schemas

### ISSUE THREAD

**Issue by gillchristian** [ferdikoomen/openapi-typescript-codegen#985]
Great tool! Thanks for all the effort.

While generating an API I found out discriminators aren't working for `oneOf` schemas that consist of a list of schemas that themselves are composed with `allOf`.

It's not easy to explain with a few words. I create a repository that reproduces the issue and explained in more detail in the readme there, comparing a working example and the case that fails.

https://github.com/gillchristian/openapi-typescript-codegen-discriminator-report

**Comment by leolabs** [comment]
@gillchristian I'm currently stuck with the same issue. Have you found a workaround for making this work in the meantime?

**Comment by leolabs** [comment]
That's a good solution!

I've come up with another one that could be helpful for some, based on your example code:

```yml
components:
  schemas:
    Base:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    One:
      allOf:
        - '$ref': '#/components/schemas/Base'
        - type: object
          required:
            - tag
            - one
          properties:
            tag:
              type: string
              enum: [one]
            one:
              type: string
    Two:
      allOf:
        - '$ref': '#/components/schemas/Base'
        - type: object
          required:
            - tag
            - two
          properties:
            tag:
              type: string
              enum: [two]
            two:
              type: string
    DiscriminatorComplex:
      discriminator:
        propertyName: tag
        mapping:
          one: '#/components/schemas/One'
          two: '#/components/schemas/Two'
      oneOf:
        - '$ref': '#/components/schemas/One'
        - '$ref': '#/components/schemas/Two'
```

If you want the `DiscriminatorType` as a type in TS, you can export it with:

```ts
export type DiscriminatorType = DiscriminatorComplex["tag"];
```
